### PR TITLE
Upgrade nightly wheels to ROCm5.6

### PR DESCRIPTION
**Pull request by jithunnair-amd**
Follow-up to https://github.com/pytorch/pytorch/pull/105076

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
torchaudio/torchvision builds are failing for ROCm5.6: https://github.com/pytorch/test-infra/actions/runs/5601869843/jobs/10246355558?pr=4401

**Comment by jithunnair-amd** [comment]
All ROCm CI jobs passed. @atalman please review and merge

**Comment by jithunnair-amd** [comment]
> All ROCm CI jobs passed. @atalman please review and merge This failure https://github.com/pytorch/test-infra/actions/runs/5601869874/job/15175252577?pr=4401 seems to be related, but not sure if a code change is needed

I think my fix worked: https://github.com/pytorch/test-infra/actions/runs/5627103250/job/15249101952?pr=4401

**Review by atalman — APPROVED** [review]
lgtm

**Pull request merged**
