### PR TITLE
Update PT2 dashboard high-lighting rules

### PR DESCRIPTION
**Pull request by huydhn**
Fixes https://github.com/pytorch/test-infra/issues/4257

The high-lighting rules are now as follows:

1. Green (OK) if the new value improves more than 5% over the old value
1. Red (Not OK) if the new value regresses more than 5% when comparing with the old value
1. Yellow (warning) if both 1 and 2 don't hold and:
    1. The new speedup value is still less than 0.95
    2. ~~Or the new compilation time is till more than 120s~~ 
    3. Or the new compression ratio is still less than 0.9

### Testing
https://torchci-git-fork-huydhn-inductor-dashboard-82c51d-fbopensource.vercel.app/benchmark/torchbench/inductor_with_cudagraphs?startTime=Sat,%2003%20Jun%202023%2001:18:34%20GMT&stopTime=Sat,%2010%20Jun%202023%2001:18:34%20GMT&granularity=hour&mode=training&dtype=amp&lBranch=main&lCommit=2961ea80f5d5fbcb9ef86d95ce08f1fa603863bf&rBranch=main&rCommit=8215468870daae5a1da7ac02f98f4e2ddf2d7623

### CODE REVIEW

**Comment by huydhn** [comment]
> Can we also get rid of the up/down red arrow? They are confusing and less informative than the highlighting rule here.

Sure, that could be easily done

**Comment by desertfire** [comment]
Another minor suggestion, the warning rule on the compilation time (the new compilation time is till more than 120s) doesn't really matter. The compilation time varies by model so an absolution threshold doesn't make much sense.

**Comment by huydhn** [comment]
> Another minor suggestion, the warning rule on the compilation time (the new compilation time is till more than 120s) doesn't really matter. The compilation time varies by model so an absolution threshold doesn't make much sense.

I see.  Let me get rid of that altogether

**Review by ezyang — APPROVED** [review]
Approving on basis of PR desc only. I briefly glanced at the code though and it looks kind of boilerplate-copy-pastey, maybe consider figuring out if there is some factorization that can happen

**Review by desertfire — APPROVED** [review]

**Pull request merged**
