### PR TITLE
Add Packer Build job for Windows AMI

### PR DESCRIPTION
**Pull request by zxiiro**
Add a job to create Windows AMIs in the PyTorch AWS Account.

Issue: pytorch/test-infra#5992

### CODE REVIEW

**Comment by atalman** [comment]
Hi @zxiiro this looks good. Would be nice to see it in action.

**Comment by zxiiro** [comment]
> Hi @zxiiro this looks good. Would be nice to see it in action.

@atalman You can see it in action here:

https://github.com/pytorch/test-infra/actions/workflows/build-windows-ami.yml

Since this PR is not yet merged we cannot use the WebUI to trigger it but I've been manually triggering it using the GitHub CLI. 

`gh workflow run 'Build Windows AMI' --ref zxiiro/windows-ami-builder -f branch=atalman-patch-15`

One issue I've been having though with this PR is even though its successfully able to create the AMI. The packer command usually hangs at the very end either after it prints:

> ==> amazon-ebs.windows_ebs_builder: Waiting for the instance to stop...

The job will fail and no AMI is created in this case.

or when it prints:

> ==> amazon-ebs.windows_ebs_builder: Waiting for AMI to become ready...

The job will timeout and fail however when I check in AWS the AMI is there so this one passes despite the failure. I'm not sure why this happens. I've only see it successfully pass twice where everything was green.

**Comment by zxiiro** [comment]
Upon further inspecting looks like the EBS volume snapshots are taking a very long time in AWS to create. I wonder if we can tell packer to not wait for AMI creation to complete and just end the job once it gets there since the EBS volume snapshots seem like it could be a background thing.

**Comment by zxiiro** [comment]
> Upon further inspecting looks like the EBS volume snapshots are taking a very long time in AWS to create. I wonder if we can tell packer to not wait for AMI creation to complete and just end the job once it gets there since the EBS volume snapshots seem like it could be a background thing.

I just saw the snapshots have completed and AMI state is now available yet the packer command is still hanging waiting for it to complete.

**Comment by zxiiro** [comment]
I think we can likely proceed with merging this since this is a manually triggered job and it does everything we need it to do despite this kinda annoying packer hang. This gets us where we want to go and we can cancel the workflow after checking that the AMI is available in AWS.

**Review by atalman — APPROVED** [review]
lgtm

**Pull request merged**
