### PR TITLE
Fix binary build setting test channel

### PR DESCRIPTION
**Pull request by atalman**
Fix binary build setting test channel

### CODE REVIEW

**Comment by atalman** [comment]
May actually not be required. Found an issue with one of the domain PR

**Review by malfet — CHANGES_REQUESTED** [review]
Hmm, can you please explain why? I.e. why if I create a branch called "malfet-likes-to-release-stuff", then any pull requests to it should upload their artifacts to release channel?

**Review by malfet — CHANGES_REQUESTED** [review]
Hmm, can you please explain why? I.e. why if I create a branch called "malfet-likes-to-release-stuff", then any pull requests to it should upload their artifacts to release channel?

**Comment by atalman** [comment]
not required

**Pull request closed without merging**
