### PR TITLE
Updated nightly wheels to ROCm5.5

### PR DESCRIPTION
**Pull request by BLOrange-AMD**

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
Follow-up to https://github.com/pytorch/pytorch/pull/102242, which enabled ROCm5.5 PyTorch wheels.

**Review by osalpekar — APPROVED** [review]
LGTM

**Review by malfet — APPROVED** [review]

**Comment by BLOrange-AMD** [comment]
ROCm builds passed and cpu builds failings are un-related error.

**Comment by jithunnair-amd** [comment]
@atalman @malfet Ready to merge?

**Pull request merged**
