### PR TITLE
Add master red percentage grouped by jobs

### PR DESCRIPTION
**Pull request by huydhn**
Adding red on master reliability metric broken down by jobs.

### Testing

https://torchci-git-fork-huydhn-add-red-percentage-48d171-fbopensource.vercel.app/reliability

### CODE REVIEW

**Comment by huydhn** [comment]
I notice that the menu is getting crowd now, so I'll follow up with another PR after this to refactor HUD menu into dropdown menu.

**Review by malfet — APPROVED** [review]
Looks good to me, but can we perhaps group it across shards? (As re-sharding makes tracking across individual shard sort of irrelevant)

**Comment by ZainRizvi** [comment]
This looks pretty cool! I'm wondering if we can make it easier to see the relevant reliability numbers for a given person without having to select each job one by one. 

Putting on a user persona hat I'm imagining one of two potential mindsets

1. I'm an Inductor dev: I want to only look at failures related to inductor jobs to make sure my tests are reliable. How can I do that without having to manually scroll through the list and click on everything that says "inductor"?

2. I'm a DevX dev: I want to know which of our workflows is least reliable in order to figure out how to fix them, and I care more about pull/trunk than I do about periodic.  I'd like to be able to easily select everything that runs in pull+trunk to view them often, and occasionally only view "periodic" jobs to check their stats.

Potential solutions to improve ease of use for of the above use cases:
- A filter box, similar to what's on the hud's home screen, to filter the jobs to the most relevant ones. Whatever matches the filter is checked automatically
- Putting a filter, or a list of boxes to have pre-checked in the query string, so that the same url always takes you to the same view
- Sorting the jobs list to put the checked items at the top (minor)

**Review by ZainRizvi — COMMENTED** [review]
This looks pretty cool! I'm wondering if we can make it easier to see the relevant reliability numbers for a given person without having to select each job one by one.

Putting on a user persona hat I'm imagining one of two potential mindsets

I'm an Inductor dev: I want to only look at failures related to inductor jobs to make sure my tests are reliable. How can I do that without having to manually scroll through the list and click on everything that says "inductor"?

I'm a DevX dev: I want to know which of our workflows is least reliable in order to figure out how to fix them, and I care more about pull/trunk than I do about periodic. I'd like to be able to easily select everything that runs in pull+trunk to view them often, and occasionally only view "periodic" jobs to check their stats.

Potential solutions to improve ease of use for of the above use cases:

- A filter box, similar to what's on the hud's home screen, to filter the jobs to the most relevant ones. Whatever matches the filter is checked automatically
- Putting a filter, or a list of boxes to have pre-checked in the query string, so that the same url always takes you to the same view
- Sorting the jobs list to put the checked items at the top (minor)

**Comment by huydhn** [comment]
> A filter box, similar to what's on the hud's home screen, to filter the jobs to the most relevant ones. Whatever matches the filter is checked automatically

Let me see if I can stretch my react skill to add a filter box :D On the other hand, the job name is actually a link, so click on that would load inductor, i.e. https://torchci-git-fork-huydhn-add-red-percentage-48d171-fbopensource.vercel.app/reliability/pytorch/pytorch?jobName=inductor%20%2F%20cuda11.6-py3.10-gcc7-sm86

**Comment by huydhn** [comment]
> * A filter box, similar to what's on the hud's home screen, to filter the jobs to the most relevant ones. Whatever matches the filter is checked automatically
> * Putting a filter, or a list of boxes to have pre-checked in the query string, so that the same url always takes you to the same view
> * Sorting the jobs list to put the checked items at the top (minor)

To make this PR more manageable, I think I will do the filter in a separate one.  This is already a big change and it's not trivial to add a similar filter like the one on main HUD page (I tried and it didn't work yet lol)

**Pull request merged**
