### PR TITLE
Increase max runners available for linux.24xl.spr-metal, linux.16xlarge.spr, linux.16xlarge.nvidia.gpu

### PR DESCRIPTION
**Pull request by jeanschmidt**

### CODE REVIEW

**Comment by jeanschmidt** [comment]
We need to be more careful and evaluate needs for runners before approving PRs.  We're having alarms going off very loudly given we're exceeding max runners for some runner types. I am as blamed for not given the proper attention to it...

two offending PRs are: https://github.com/pytorch/test-infra/pull/5283 https://github.com/pytorch/test-infra/pull/5089

FYI
@ZainRizvi @zxd1997066 @chuanqi129 @atalman @tylertitsworth @malfet

**Comment by malfet** [comment]
Hmm, having some queue on those types of runners sounds ok to me, as they are only used in opt-in workflows.

**Comment by chuanqi129** [comment]
Hi @jeanschmidt, sorry for the inconvenience, seems our resource cost evaluation method used for those 2 PRs is not quite accurate.

**Comment by jeanschmidt** [comment]
@malfet this max_runner is a overprovision protection, think about a cap that prevents Meta to pay Amazon lots of money if a bug is ever deployed that makes lambdas create thousands of instances.

This number should be always higher than the maximum projected possible peak.

As we have a flat rate per hour, 2 instances used for 1h will cost the same as 1 instance used by 2h. But the second option is faster, so we might not even want to cap the runners in this way as there should not be any benefits in costs.

**Comment by jeanschmidt** [comment]
@chuanqi129 I also forgot to verify if those numbers are accurate :)

**Comment by chuanqi129** [comment]
Hi @jeanschmidt, could you please help to check the issue mentioned in https://github.com/pytorch/pytorch/issues/126993#issuecomment-2196173627? Does it mean we can't use this type instance as GHA runner?

**Pull request merged**
