### PR TITLE
Add scripts to build windows GHA AMIs

### PR DESCRIPTION
**Pull request by seemethere**
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

### CODE REVIEW

**Comment by zhouzhuojie** [comment]
Nice! Can I also suggest a new directory for it? e.g. `aws/ami/windows` instead of `virtual-environments`

**Comment by seemethere** [comment]
> Nice! Can I also suggest a new directory for it? e.g. `aws/ami/windows` instead of `virtual-environments`

Done!

**Comment by zhouzhuojie** [comment]
> Nice! Can I also suggest a new directory for it? e.g. `aws/ami/windows` instead of `virtual-environments`

oh, nvm, actually packer can deploy to more than aws ami with json configurations, this looks good

**Review by zhouzhuojie — APPROVED** [review]
lgtm, we can refactor it later if we do need to support other cloud vendors

**Pull request merged**
