### PR TITLE
remove functionality from pr review/edited

### PR DESCRIPTION
**Pull request by zengk95**
Addresses https://github.com/pytorch/test-infra/issues/359

### CODE REVIEW

**Comment by malfet** [comment]
@kit1980 added this functionality in #233 as result of feature request in https://github.com/pytorch/pytorch/issues/72749

**Comment by kit1980** [comment]
Given that Microsoft is our strategic partner for GitHub First, and the feature was requested by them (ONNX team specifically), I don't think we should remove this functionality.

**Comment by suo** [comment]
I mean, I don't think they will care that much if we remove it, as long as we tell them why. But I'm fine to make it work as well; @zengk95 it's your call

**Comment by zengk95** [comment]
closing this since some amount of people ~20 are using this after querying rockset. 

I'll port it over in a bit.

**Pull request closed without merging**
