### PR TITLE
Fix update slow tests GHA workflow by using legit username/email

### PR DESCRIPTION
**Pull request by janeyx99**
Would resolve a broken run such as: https://github.com/pytorch/test-infra/actions/runs/720431754

Bigger question: is there a team email/team git user we could use?

### CODE REVIEW

**Review by walterddr — CHANGES_REQUESTED** [review]
I dont think that was the reason
`destination_branch` needs to be added

**Comment by janeyx99** [comment]
> I dont think that was the reason
> `destination_branch` needs to be added

You are so right

**Comment by janeyx99** [comment]
Wow i did not read properly

**Comment by walterddr** [comment]
I think the default was not "master" as how the README suggested. it seems like it has moved on to be named "main"

Error log: 
```
+ git clone --single-branch --branch main ***github.com/pytorch/test-infra.git /tmp/tmp.mpGIej
Cloning destination git repository
Cloning into '/tmp/tmp.mpGIej'...
warning: Could not find remote branch main to clone.
fatal: Remote branch main not found in upstream origin
```

**Comment by janeyx99** [comment]
> I think the default was not "master" as how the README suggested. it seems like it has moved on to be named "main"
> 
> Error log:
> 
> ```
> + git clone --single-branch --branch main ***github.com/pytorch/test-infra.git /tmp/tmp.mpGIej
> Cloning destination git repository
> Cloning into '/tmp/tmp.mpGIej'...
> warning: Could not find remote branch main to clone.
> fatal: Remote branch main not found in upstream origin
> ```

Yea I realized--just fixed it

**Review by walterddr — APPROVED** [review]

**Pull request merged**
