### PR TITLE
Update scripts to ROCm5.3

### PR DESCRIPTION
**Pull request by jithunnair-amd**
Needed for https://github.com/pytorch/vision/pull/6955

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@atalman Do I need to make any other changes to any other files as part of this PR?

**Comment by osalpekar** [comment]
Thanks @jithunnair-amd! This should be good enough to move all the the nightly wheels across most of the domain libraries to the new rocm versions.

**Comment by jithunnair-amd** [comment]
Thanks @osalpekar, that sounds great. Would you mind elaborating a bit more on the vision forward for building nightly wheels? Some specific questions:
1. Will this strategy eventually cover PyTorch nightly wheels as well, or only domain libraries such as vision, audio etc.? (so that we will not need to make some of the changes to switch to ROCm5.3 as in PRs https://github.com/pytorch/builder/pull/1193 and https://github.com/pytorch/pytorch/pull/89101?)
2. Will PRs such as this become unnecessary going forward? https://github.com/pytorch/vision/pull/6955

**Comment by osalpekar** [comment]
@jithunnair-amd Sure thing. There are 3 main components at work:
* Build matrix generation script in test-infra - which you've touched in this PR
* Reusable build workflows. For example, this is a general workflow for building Linux Wheels: https://github.com/pytorch/test-infra/blob/main/.github/workflows/build_wheels_linux.yml. This will consume the build matrix generated by the script and build/publish wheels for nightlies and releases.
* Caller workflows. These are workflows in the domain repos like: https://github.com/pytorch/vision/blob/main/.github/workflows/build-wheels-linux.yml. These basically just call the reusable workflows with any domain-specific hooks.

Re your questions:
1. The plan is to use this across the entire PyTorch ecosystem! PyTorch core will use the existing method, but all the other repos will use these build components. At the moment, we've migrated torchtext, torchvision, and torchrec to this new workflow (deprecating CircleCI builds along the way). We're hoping to migrate torchaudio and torchdata in the coming few weeks. The remaining libraries are scheduled for migration early next year.
2. That's right! Once the migration is all done, changing the versions in this build script will ensure the new versions are used across the whole ecosystem, so those PR's in each domain library will not be needed. (In fact, that is one of the reasons we're moving to this workflow.) However, until the migration is done, those PR's in each repo will be needed.

**Review by osalpekar — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@osalpekar Anything else needed to merge this PR? Thanks!

**Comment by osalpekar** [comment]
@jithunnair-amd yep, good to go!

**Pull request merged**
