### PR TITLE
add persistent grouping

### PR DESCRIPTION
**Pull request by clee2000**
Add mem_leak_check as a persistent group in the hud

Other changes:
* use more maps/dictionaries

### CODE REVIEW

**Comment by ZainRizvi** [comment]
Is the hud expected to show any differences before your ["Disable mem leak check](https://github.com/pytorch/pytorch/pull/88373/files) PR is merged?

The preview page looks identical to the prod HUD

**Comment by clee2000** [comment]
> Is the hud expected to show any differences before your ["Disable mem leak check](https://github.com/pytorch/pytorch/pull/88373/files) PR is merged?
> 
> The preview page looks identical to the prod HUD

No, it's not expected to show any differences yet

**Review by huydhn — APPROVED** [review]
LGTM! May be merge https://github.com/pytorch/pytorch/pull/88373 first to see the gnew group pop up before merging this one?

**Review by ZainRizvi — APPROVED** [review]
+1 to Huy's suggestion. Let's merge the other PR first to git a visual confirmation that this one works before merging it :)

**Pull request merged**
