### PR TITLE
[rebasebot] Add check for first time contributor

### PR DESCRIPTION
**Pull request by clee2000**
idk if this is the right definition of first time contributor but if we define it  as someone who has never authored a commit to the default branch, then we can query for commits on the default branch with the author as the commenter.  If there are no commits, then the commenter is a first time contributor.

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
The `isFirstTimeContributor` check looks fine to me.  On the other hand, I thought graduating from being a first time contributor means having write permission, i.e. `hasWritePermissions` and `!isFirstTimeContributor` is the same thing?  Do you know a case where not a first time contributor doesn't have write permission?

**Review by malfet — APPROVED** [review]
Sure, but kind of meta question - what's the difference between `lib/bot/utils.ts` and `lib/bot/botUtils.ts`? Perhaps some short explanation can be added to the header. And if none, just merge the two (imo `bot` prefix is sort of redundant for files in `lib/bot` folder, isn't it?)

**Comment by malfet** [comment]
> The `isFirstTimeContributor` check looks fine to me. On the other hand, I thought graduating from being a first time contributor means having write permission, i.e. `hasWritePermissions` and `!isFirstTimeContributor` is the same thing? Do you know a case where not a first time contributor doesn't have write permission?

Only members of `pytorch/pytorch` has write permissions. I.e. you can be a regular contributor but do not have write permissions to the repo they are contributing.(but should have a write permissions to their own repo)
 Which probably raises a good question: `hasWritePermissions` checks if one have perms to PR target or PR origin?

**Comment by clee2000** [comment]
> Which probably raises a good question: hasWritePermissions checks if one have perms to PR target or PR origin?

I believe it's PR target b/c the check uses ctx.payload.repository.etc, also if it used origin, wouldn't people would always pass the check

**Comment by ZainRizvi** [comment]
> The `isFirstTimeContributor` check looks fine to me. On the other hand, I thought graduating from being a first time contributor means having write permission, i.e. `hasWritePermissions` and `!isFirstTimeContributor` is the same thing? Do you know a case where not a first time contributor doesn't have write permission?

They're not quite the same. hasWritePermisssions means someone has write access to the repository, which allows them to do things like add labels to their PR.

The main perk of being a non-first time contributor (I think) is that you no longer need approvals before CI runs against your PR

**Pull request merged**
