### PR TITLE
Update generate_binary_build_matrix.py to ROCm 5.4.2

### PR DESCRIPTION
**Pull request by BLOrange-AMD**

### CODE REVIEW

**Comment by BLOrange-AMD** [comment]
@atalman @kit1980 @malfet Could you please help to review this PR? Thanks!

**Review by malfet — APPROVED** [review]

**Review by malfet — CHANGES_REQUESTED** [review]
Actually, you could only change nightly configurations, release must not be changed until next release is out

**Comment by BLOrange-AMD** [comment]
> Actually, you could only change nightly configurations, release must not be changed until next release is out

Thanks. Changes made accordingly.

**Comment by jithunnair-amd** [comment]
cc @atalman

**Review by atalman — APPROVED** [review]
LGTM

**Review by atalman — APPROVED** [review]
LGTM

**Pull request merged**
