### PR TITLE
Add SAM to blueberries dashboard

### PR DESCRIPTION
**Pull request by msaroufim**

### CODE REVIEW

**Comment by huydhn** [comment]
Double check with @msaroufim that TorchBench `sam` model hasn't been run recently in the CI.  I grab the run on Monday https://hud.pytorch.org/pytorch/pytorch/commit/07107919297db3f8ab37f11c12666b6d6d5f692e but couldn't find it in any of the test reports.  @desertfire Do you have any insights on this?

**Comment by msaroufim** [comment]
Hi @huydhn so I merged this https://github.com/pytorch/pytorch/pull/105222 which fixes the eager sam failure but still don't see it reflected in dashboard preview here - do i need to wait a day to see data refreshed or did i miss something?

**Comment by huydhn** [comment]
> Hi @huydhn so I merged this [pytorch/pytorch#105222](https://github.com/pytorch/pytorch/pull/105222) which fixes the eager sam failure but still don't see it reflected in dashboard preview here - do i need to wait a day to see data refreshed or did i miss something?

Yup, that's the case as I can see `nanogtp` and `llama` there.  If you go to https://hud.pytorch.org/hud/pytorch/pytorch/main/1?per_page=50&name_filter=nductor-A100-perf-nightly, you could see when was the last time the nightly perf benchmark run.

The other way is to manually start the job right away https://github.com/pytorch/pytorch/actions/workflows/inductor-perf-test-nightly.yml.  The queue job will be run as soon as the runners become available.

**Review by huydhn — APPROVED** [review]

**Comment by huydhn** [comment]
Please run `yarn format` to pass the check and this is ready to go :)

**Pull request merged**
