### PR TITLE
add a script to analyze git history for a repo

### PR DESCRIPTION
**Pull request by dagitses**

### CODE REVIEW

**Review by osalpekar — COMMENTED** [review]
Is the plan to run this on each PR with `commit_id` being the most recent commit and `limit` being the number of commits in the PR?

**Comment by dagitses** [comment]
> Is the plan to run this on each PR with `commit_id` being the most recent commit and `limit` being the number of commits in the PR?

No, this is just a script for offline analysis: what *would* have happened. It can also be used after the fact to see what a user should have seen.

**Review by osalpekar — APPROVED** [review]

**Comment by dagitses** [comment]
#1119 . Accidentally merged this into check_commit branch.

**Comment by dagitses** [comment]
er, #1120.

**Pull request merged**
